### ISSUE TITLE
Command Parsing Enhancements

### ISSUE THREAD

**Issue by WizardLink** [Hydractify/Kanna-Kobayashi#23]
### All commands presented here *should* get better parsing or functionality when parsing

---

### EmojiCommand / Role / User
- [ ] Show more than a single result
> _User case we have to first see if it would be a good thing to implement, and if so, when finding an exact match, not showing the other matches._
---

### WeebCommand
- [ ] space parsing to `or`, `,` `and` parsing (Like done in the choose command a963e2955a53683a766481814c4e758920222b8e)

---

More commands and the respective tasks will be added over time.

**Comment by WizardLink** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Command Parsing Enhancements](https://trello.com/c/3don2DmQ/3-command-parsing-enhancements)

**Comment by wizardlink** [comment]
It has been too long.
